DROP TABLE address;
DROP TABLE address_association;
DROP TABLE bike;
DROP TABLE bike_location;
DROP TABLE bill;
DROP TABLE bill_transaction;
DROP TABLE license_policy;
DROP TABLE organization;
DROP TABLE payment_info;
DROP TABLE payment_transaction;
DROP TABLE permission;
DROP TABLE program;
DROP TABLE rent_transation;
DROP TABLE role;
DROP TABLE role_permission;
DROP TABLE station;
DROP TABLE subscription_policy;
DROP TABLE subscription_rate;
DROP TABLE tenant;
DROP TABLE tenant_license_policy;
DROP TABLE user;
DROP TABLE user_role;
DROP TABLE user_subscription_policy;

CREATE TABLE user (id int(10) NOT NULL AUTO_INCREMENT, user_name varchar(30), program_id int(10), tenant_id int(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE tenant (id int(10) NOT NULL AUTO_INCREMENT, tenant_name varchar(30), contact_id int(10),version int(11), PRIMARY KEY (id));
CREATE TABLE organization (id int(10) NOT NULL AUTO_INCREMENT, org_name varchar(30), tenant_id int(10) NOT NULL, contact_id int(10), `Column` int(10), version int(11),PRIMARY KEY (id));
CREATE TABLE program (id int(10) NOT NULL AUTO_INCREMENT, program_name varchar(60), program_description varchar(255), tenant_id int(10) NOT NULL, org_id int(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE station (id int(10) NOT NULL AUTO_INCREMENT, location varchar(20), tenant_id int(10) NOT NULL, program_id int(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE bike (id int(10) NOT NULL AUTO_INCREMENT, bike_height int(10) NOT NULL, bike_color varchar(20) NOT NULL, bike_type varchar(20) NOT NULL, last_service_date date, wheel_size varchar(50) NOT NULL, bike_status varchar(60) NOT NULL, tenant_id int(10) NULL, PRIMARY KEY (id));
CREATE TABLE bike_location (id int(10) NOT NULL AUTO_INCREMENT,bike_status varchar(20), bike_id int(10), station_id int(10) NOT NULL,version int(11), PRIMARY KEY (id));
CREATE TABLE address (id int(10) NOT NULL AUTO_INCREMENT, addr1 varchar(255) NOT NULL, addr2 varchar(255), city varchar(30) NOT NULL, state varchar(30) NOT NULL, country varchar(30) NOT NULL, zip_code varchar(10) NOT NULL, cell_phone varchar(60), address_type varchar(50) NOT NULL, work_phone varchar(60), entity_id int(10), entity_type varchar(60), user_id int(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE payment_info (id int(10) NOT NULL AUTO_INCREMENT, card_number varchar(20), card_type varchar(20), card_user_name varchar(50), user_id int(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE user_role (id int(10) NOT NULL AUTO_INCREMENT,user_id int(10) NOT NULL, role_id int(10),PRIMARY KEY (id));
CREATE TABLE rent_transation (id int(10) NOT NULL AUTO_INCREMENT, from_station_id int(10), to_station_id int(10), bike_id int(10), user_id int(10) NOT NULL, tenant_id int(10), rent_start_date date, rate_id int(10), rent_end_date date, status varchar(60), comments varchar(250),PRIMARY KEY (id));
CREATE TABLE role (id int(10) NOT NULL AUTO_INCREMENT, role_name varchar(50) NOT NULL, PRIMARY KEY (id));
CREATE TABLE subscription_policy (id int(10) NOT NULL AUTO_INCREMENT, policy_name varchar(60), policy_description varchar(60), policy_type varchar(50), program_id int(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE permission (id int(10) NOT NULL AUTO_INCREMENT, permission_name varchar(60), description varchar(255),version int(11), PRIMARY KEY (id));
CREATE TABLE role_permission (id int(10) NOT NULL AUTO_INCREMENT, permission_id int(10) NOT NULL, role_id int(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE license_policy (id int(10) NOT NULL AUTO_INCREMENT, license_name varchar(250), license_cost_peruser double, license_type int(10), license_base_cost double, free_trial_period_in_days int(10), PRIMARY KEY (id));
CREATE TABLE tenant_license_policy (id int(10) NOT NULL AUTO_INCREMENT,license_id int(10) NOT NULL, tenant_id int(10) NOT NULL, license_start_date date, license_end_date date, is_trial int(10), PRIMARY KEY(id));
CREATE TABLE user_subscription_policy (id int(10) NOT NULL AUTO_INCREMENT,user_id int(10) NOT NULL, policy_id int(10) NOT NULL, PRIMARY KEY(id));
CREATE TABLE subscription_rate (id int(10) NOT NULL AUTO_INCREMENT, membership_permonth double, organization_share double, user_share double, free_minutes_perday int(10), extra_charges_perminute double, policy_start_date date, policy_end_date date, policy_id int(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE bill_transaction (id int(10) NOT NULL AUTO_INCREMENT, total_cost double, bill_id int(10) NOT NULL, transaction_type varchar(50), start_date date, end_date date, description varchar(255), PRIMARY KEY (id));
CREATE TABLE bill (id int(10) NOT NULL AUTO_INCREMENT, total_charges int(10), description varchar(255), created_date date, bill_start_date date, bill_end_date date, tenant_id int(10), user_id int(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE address_association (id int(10) NOT NULL AUTO_INCREMENT,entity_id int(10), address_id int(10) NOT NULL, entity_type int(10),PRIMARY KEY (id));
CREATE TABLE payment_transaction (id int(10) NOT NULL AUTO_INCREMENT, status int(10), date_of_transaction int(10), user_id int(10) NOT NULL, payment_id int(10) NOT NULL, bill_id int(10) NOT NULL, PRIMARY KEY (id));
ALTER TABLE payment_info ADD INDEX FKpayment_in938275 (user_id), ADD CONSTRAINT FKpayment_in938275 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE user ADD INDEX FKuser330759 (tenant_id), ADD CONSTRAINT FKuser330759 FOREIGN KEY (tenant_id) REFERENCES tenant (id);
ALTER TABLE program ADD INDEX FKprogram318023 (tenant_id), ADD CONSTRAINT FKprogram318023 FOREIGN KEY (tenant_id) REFERENCES tenant (id);
ALTER TABLE bike ADD INDEX FKbike906225 (tenant_id), ADD CONSTRAINT FKbike906225 FOREIGN KEY (tenant_id) REFERENCES tenant (id);
ALTER TABLE station ADD INDEX FKstation903803 (tenant_id), ADD CONSTRAINT FKstation903803 FOREIGN KEY (tenant_id) REFERENCES tenant (id);
ALTER TABLE organization ADD INDEX FKorganizati993399 (tenant_id), ADD CONSTRAINT FKorganizati993399 FOREIGN KEY (tenant_id) REFERENCES tenant (id);
ALTER TABLE bike_location ADD INDEX FKbike_locat442826 (bike_id), ADD CONSTRAINT FKbike_locat442826 FOREIGN KEY (bike_id) REFERENCES bike (id);
ALTER TABLE bike_location ADD INDEX FKbike_locat282148 (station_id), ADD CONSTRAINT FKbike_locat282148 FOREIGN KEY (station_id) REFERENCES station (id);
ALTER TABLE user_role ADD INDEX FKuser_role807043 (user_id), ADD CONSTRAINT FKuser_role807043 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE rent_transation ADD INDEX FKrent_trans366470 (user_id), ADD CONSTRAINT FKrent_trans366470 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE rent_transation ADD INDEX FKrent_trans618708 (bike_id), ADD CONSTRAINT FKrent_trans618708 FOREIGN KEY (bike_id) REFERENCES bike (id);
ALTER TABLE user_role ADD INDEX FKuser_role220486 (role_id), ADD CONSTRAINT FKuser_role220486 FOREIGN KEY (role_id) REFERENCES role (id);
ALTER TABLE subscription_policy ADD INDEX FKsubscripti157516 (program_id), ADD CONSTRAINT FKsubscripti157516 FOREIGN KEY (program_id) REFERENCES program (id);
ALTER TABLE role_permission ADD INDEX FKrole_permi451547 (role_id), ADD CONSTRAINT FKrole_permi451547 FOREIGN KEY (role_id) REFERENCES role (id);
ALTER TABLE role_permission ADD INDEX FKrole_permi183089 (permission_id), ADD CONSTRAINT FKrole_permi183089 FOREIGN KEY (permission_id) REFERENCES permission (id);
ALTER TABLE tenant_license_policy ADD INDEX FKtenant_lic996616 (license_id), ADD CONSTRAINT FKtenant_lic996616 FOREIGN KEY (license_id) REFERENCES license_policy (id);
ALTER TABLE tenant_license_policy ADD INDEX FKtenant_lic646131 (tenant_id), ADD CONSTRAINT FKtenant_lic646131 FOREIGN KEY (tenant_id) REFERENCES tenant (id);
ALTER TABLE subscription_rate ADD INDEX FKsubscripti703864 (policy_id), ADD CONSTRAINT FKsubscripti703864 FOREIGN KEY (policy_id) REFERENCES subscription_policy (id);
ALTER TABLE bill_transaction ADD INDEX FKbill_trans447579 (bill_id), ADD CONSTRAINT FKbill_trans447579 FOREIGN KEY (bill_id) REFERENCES bill (id);
ALTER TABLE bill ADD INDEX FKbill642927 (user_id), ADD CONSTRAINT FKbill642927 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE address_association ADD INDEX FKaddress_as240280 (address_id), ADD CONSTRAINT FKaddress_as240280 FOREIGN KEY (address_id) REFERENCES address (id);
ALTER TABLE address ADD INDEX FKaddress360001 (user_id), ADD CONSTRAINT FKaddress360001 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE user_subscription_policy ADD INDEX FKuser_subsc833909 (user_id), ADD CONSTRAINT FKuser_subsc833909 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE user_subscription_policy ADD INDEX FKuser_subsc847371 (policy_id), ADD CONSTRAINT FKuser_subsc847371 FOREIGN KEY (policy_id) REFERENCES subscription_policy (id);
ALTER TABLE station ADD INDEX FKstation306681 (program_id), ADD CONSTRAINT FKstation306681 FOREIGN KEY (program_id) REFERENCES program (id);
ALTER TABLE payment_transaction ADD INDEX FKpayment_tr290075 (user_id), ADD CONSTRAINT FKpayment_tr290075 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE payment_transaction ADD INDEX FKpayment_tr494181 (payment_id), ADD CONSTRAINT FKpayment_tr494181 FOREIGN KEY (id) REFERENCES payment_info (id);
ALTER TABLE payment_transaction ADD INDEX FKpayment_tr669597 (bill_id), ADD CONSTRAINT FKpayment_tr669597 FOREIGN KEY (bill_id) REFERENCES bill (id);
ALTER TABLE program ADD INDEX FKprogram840536 (org_id), ADD CONSTRAINT FKprogram840536 FOREIGN KEY (org_id) REFERENCES organization (id);



