// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.AddressAssociationDataOnDemand;
import com.sjsu.bikelet.domain.AddressAssociationIntegrationTest;
import com.sjsu.bikelet.service.AddressAssociationService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AddressAssociationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AddressAssociationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AddressAssociationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AddressAssociationIntegrationTest: @Transactional;
    
    @Autowired
    AddressAssociationDataOnDemand AddressAssociationIntegrationTest.dod;
    
    @Autowired
    AddressAssociationService AddressAssociationIntegrationTest.addressAssociationService;
    
    @Test
    public void AddressAssociationIntegrationTest.testCountAllAddressAssociations() {
        Assert.assertNotNull("Data on demand for 'AddressAssociation' failed to initialize correctly", dod.getRandomAddressAssociation());
        long count = addressAssociationService.countAllAddressAssociations();
        Assert.assertTrue("Counter for 'AddressAssociation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AddressAssociationIntegrationTest.testFindAddressAssociation() {
        AddressAssociation obj = dod.getRandomAddressAssociation();
        Assert.assertNotNull("Data on demand for 'AddressAssociation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AddressAssociation' failed to provide an identifier", id);
        obj = addressAssociationService.findAddressAssociation(id);
        Assert.assertNotNull("Find method for 'AddressAssociation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AddressAssociation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AddressAssociationIntegrationTest.testFindAllAddressAssociations() {
        Assert.assertNotNull("Data on demand for 'AddressAssociation' failed to initialize correctly", dod.getRandomAddressAssociation());
        long count = addressAssociationService.countAllAddressAssociations();
        Assert.assertTrue("Too expensive to perform a find all test for 'AddressAssociation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AddressAssociation> result = addressAssociationService.findAllAddressAssociations();
        Assert.assertNotNull("Find all method for 'AddressAssociation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AddressAssociation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AddressAssociationIntegrationTest.testFindAddressAssociationEntries() {
        Assert.assertNotNull("Data on demand for 'AddressAssociation' failed to initialize correctly", dod.getRandomAddressAssociation());
        long count = addressAssociationService.countAllAddressAssociations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AddressAssociation> result = addressAssociationService.findAddressAssociationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AddressAssociation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AddressAssociation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AddressAssociationIntegrationTest.testFlush() {
        AddressAssociation obj = dod.getRandomAddressAssociation();
        Assert.assertNotNull("Data on demand for 'AddressAssociation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AddressAssociation' failed to provide an identifier", id);
        obj = addressAssociationService.findAddressAssociation(id);
        Assert.assertNotNull("Find method for 'AddressAssociation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAddressAssociation(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AddressAssociation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AddressAssociationIntegrationTest.testUpdateAddressAssociationUpdate() {
        AddressAssociation obj = dod.getRandomAddressAssociation();
        Assert.assertNotNull("Data on demand for 'AddressAssociation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AddressAssociation' failed to provide an identifier", id);
        obj = addressAssociationService.findAddressAssociation(id);
        boolean modified =  dod.modifyAddressAssociation(obj);
        Integer currentVersion = obj.getVersion();
        AddressAssociation merged = addressAssociationService.updateAddressAssociation(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AddressAssociation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AddressAssociationIntegrationTest.testSaveAddressAssociation() {
        Assert.assertNotNull("Data on demand for 'AddressAssociation' failed to initialize correctly", dod.getRandomAddressAssociation());
        AddressAssociation obj = dod.getNewTransientAddressAssociation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AddressAssociation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AddressAssociation' identifier to be null", obj.getId());
        addressAssociationService.saveAddressAssociation(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'AddressAssociation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AddressAssociationIntegrationTest.testDeleteAddressAssociation() {
        AddressAssociation obj = dod.getRandomAddressAssociation();
        Assert.assertNotNull("Data on demand for 'AddressAssociation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AddressAssociation' failed to provide an identifier", id);
        obj = addressAssociationService.findAddressAssociation(id);
        addressAssociationService.deleteAddressAssociation(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'AddressAssociation' with identifier '" + id + "'", addressAssociationService.findAddressAssociation(id));
    }
    
}
