// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.AddressAssociation;
import com.sjsu.bikelet.domain.AddressAssociationDataOnDemand;
import com.sjsu.bikelet.service.AddressAssociationService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AddressAssociationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AddressAssociationDataOnDemand: @Component;
    
    private Random AddressAssociationDataOnDemand.rnd = new SecureRandom();
    
    private List<AddressAssociation> AddressAssociationDataOnDemand.data;
    
    @Autowired
    AddressAssociationService AddressAssociationDataOnDemand.addressAssociationService;
    
    public AddressAssociation AddressAssociationDataOnDemand.getNewTransientAddressAssociation(int index) {
        AddressAssociation obj = new AddressAssociation();
        setAddressId(obj, index);
        setEntityId(obj, index);
        setEntityType(obj, index);
        return obj;
    }
    
    public void AddressAssociationDataOnDemand.setAddressId(AddressAssociation obj, int index) {
        Integer addressId = new Integer(index);
        obj.setAddressId(addressId);
    }
    
    public void AddressAssociationDataOnDemand.setEntityId(AddressAssociation obj, int index) {
        Integer entityId = new Integer(index);
        obj.setEntityId(entityId);
    }
    
    public void AddressAssociationDataOnDemand.setEntityType(AddressAssociation obj, int index) {
        Integer entityType = new Integer(index);
        obj.setEntityType(entityType);
    }
    
    public AddressAssociation AddressAssociationDataOnDemand.getSpecificAddressAssociation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AddressAssociation obj = data.get(index);
        Long id = obj.getId();
        return addressAssociationService.findAddressAssociation(id);
    }
    
    public AddressAssociation AddressAssociationDataOnDemand.getRandomAddressAssociation() {
        init();
        AddressAssociation obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return addressAssociationService.findAddressAssociation(id);
    }
    
    public boolean AddressAssociationDataOnDemand.modifyAddressAssociation(AddressAssociation obj) {
        return false;
    }
    
    public void AddressAssociationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = addressAssociationService.findAddressAssociationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AddressAssociation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AddressAssociation>();
        for (int i = 0; i < 10; i++) {
            AddressAssociation obj = getNewTransientAddressAssociation(i);
            try {
                addressAssociationService.saveAddressAssociation(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
