// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.BikeLetRole;
import com.sjsu.bikelet.domain.BikeLetRoleDataOnDemand;
import com.sjsu.bikelet.domain.BikeLetRoleIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BikeLetRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BikeLetRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BikeLetRoleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BikeLetRoleIntegrationTest: @Transactional;
    
    @Autowired
    BikeLetRoleDataOnDemand BikeLetRoleIntegrationTest.dod;
    
    @Test
    public void BikeLetRoleIntegrationTest.testCountBikeLetRoles() {
        Assert.assertNotNull("Data on demand for 'BikeLetRole' failed to initialize correctly", dod.getRandomBikeLetRole());
        long count = BikeLetRole.countBikeLetRoles();
        Assert.assertTrue("Counter for 'BikeLetRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BikeLetRoleIntegrationTest.testFindBikeLetRole() {
        BikeLetRole obj = dod.getRandomBikeLetRole();
        Assert.assertNotNull("Data on demand for 'BikeLetRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BikeLetRole' failed to provide an identifier", id);
        obj = BikeLetRole.findBikeLetRole(id);
        Assert.assertNotNull("Find method for 'BikeLetRole' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BikeLetRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BikeLetRoleIntegrationTest.testFindAllBikeLetRoles() {
        Assert.assertNotNull("Data on demand for 'BikeLetRole' failed to initialize correctly", dod.getRandomBikeLetRole());
        long count = BikeLetRole.countBikeLetRoles();
        Assert.assertTrue("Too expensive to perform a find all test for 'BikeLetRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BikeLetRole> result = BikeLetRole.findAllBikeLetRoles();
        Assert.assertNotNull("Find all method for 'BikeLetRole' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BikeLetRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BikeLetRoleIntegrationTest.testFindBikeLetRoleEntries() {
        Assert.assertNotNull("Data on demand for 'BikeLetRole' failed to initialize correctly", dod.getRandomBikeLetRole());
        long count = BikeLetRole.countBikeLetRoles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BikeLetRole> result = BikeLetRole.findBikeLetRoleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BikeLetRole' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BikeLetRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BikeLetRoleIntegrationTest.testFlush() {
        BikeLetRole obj = dod.getRandomBikeLetRole();
        Assert.assertNotNull("Data on demand for 'BikeLetRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BikeLetRole' failed to provide an identifier", id);
        obj = BikeLetRole.findBikeLetRole(id);
        Assert.assertNotNull("Find method for 'BikeLetRole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBikeLetRole(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'BikeLetRole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BikeLetRoleIntegrationTest.testMergeUpdate() {
        BikeLetRole obj = dod.getRandomBikeLetRole();
        Assert.assertNotNull("Data on demand for 'BikeLetRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BikeLetRole' failed to provide an identifier", id);
        obj = BikeLetRole.findBikeLetRole(id);
        boolean modified =  dod.modifyBikeLetRole(obj);
        Integer currentVersion = obj.getVersion();
        BikeLetRole merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BikeLetRole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BikeLetRoleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'BikeLetRole' failed to initialize correctly", dod.getRandomBikeLetRole());
        BikeLetRole obj = dod.getNewTransientBikeLetRole(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BikeLetRole' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BikeLetRole' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'BikeLetRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BikeLetRoleIntegrationTest.testRemove() {
        BikeLetRole obj = dod.getRandomBikeLetRole();
        Assert.assertNotNull("Data on demand for 'BikeLetRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BikeLetRole' failed to provide an identifier", id);
        obj = BikeLetRole.findBikeLetRole(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'BikeLetRole' with identifier '" + id + "'", BikeLetRole.findBikeLetRole(id));
    }
    
}
