// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.BikeLetUser;
import com.sjsu.bikelet.domain.BikeLetUserDataOnDemand;
import com.sjsu.bikelet.domain.BikeLetUserIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BikeLetUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BikeLetUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BikeLetUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BikeLetUserIntegrationTest: @Transactional;
    
    @Autowired
    BikeLetUserDataOnDemand BikeLetUserIntegrationTest.dod;
    
    @Test
    public void BikeLetUserIntegrationTest.testCountBikeLetUsers() {
        Assert.assertNotNull("Data on demand for 'BikeLetUser' failed to initialize correctly", dod.getRandomBikeLetUser());
        long count = BikeLetUser.countBikeLetUsers();
        Assert.assertTrue("Counter for 'BikeLetUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BikeLetUserIntegrationTest.testFindBikeLetUser() {
        BikeLetUser obj = dod.getRandomBikeLetUser();
        Assert.assertNotNull("Data on demand for 'BikeLetUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BikeLetUser' failed to provide an identifier", id);
        obj = BikeLetUser.findBikeLetUser(id);
        Assert.assertNotNull("Find method for 'BikeLetUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BikeLetUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BikeLetUserIntegrationTest.testFindAllBikeLetUsers() {
        Assert.assertNotNull("Data on demand for 'BikeLetUser' failed to initialize correctly", dod.getRandomBikeLetUser());
        long count = BikeLetUser.countBikeLetUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'BikeLetUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BikeLetUser> result = BikeLetUser.findAllBikeLetUsers();
        Assert.assertNotNull("Find all method for 'BikeLetUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BikeLetUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BikeLetUserIntegrationTest.testFindBikeLetUserEntries() {
        Assert.assertNotNull("Data on demand for 'BikeLetUser' failed to initialize correctly", dod.getRandomBikeLetUser());
        long count = BikeLetUser.countBikeLetUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BikeLetUser> result = BikeLetUser.findBikeLetUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BikeLetUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BikeLetUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BikeLetUserIntegrationTest.testFlush() {
        BikeLetUser obj = dod.getRandomBikeLetUser();
        Assert.assertNotNull("Data on demand for 'BikeLetUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BikeLetUser' failed to provide an identifier", id);
        obj = BikeLetUser.findBikeLetUser(id);
        Assert.assertNotNull("Find method for 'BikeLetUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBikeLetUser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'BikeLetUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BikeLetUserIntegrationTest.testMergeUpdate() {
        BikeLetUser obj = dod.getRandomBikeLetUser();
        Assert.assertNotNull("Data on demand for 'BikeLetUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BikeLetUser' failed to provide an identifier", id);
        obj = BikeLetUser.findBikeLetUser(id);
        boolean modified =  dod.modifyBikeLetUser(obj);
        Integer currentVersion = obj.getVersion();
        BikeLetUser merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BikeLetUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BikeLetUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'BikeLetUser' failed to initialize correctly", dod.getRandomBikeLetUser());
        BikeLetUser obj = dod.getNewTransientBikeLetUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BikeLetUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BikeLetUser' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'BikeLetUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BikeLetUserIntegrationTest.testRemove() {
        BikeLetUser obj = dod.getRandomBikeLetUser();
        Assert.assertNotNull("Data on demand for 'BikeLetUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BikeLetUser' failed to provide an identifier", id);
        obj = BikeLetUser.findBikeLetUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'BikeLetUser' with identifier '" + id + "'", BikeLetUser.findBikeLetUser(id));
    }
    
}
