// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.BikeLetRole;
import com.sjsu.bikelet.domain.RolePermission;
import com.sjsu.bikelet.domain.RolePermissionDataOnDemand;
import com.sjsu.bikelet.domain.UserRole;
import com.sjsu.bikelet.domain.UserRoleDataOnDemand;
import java.lang.Integer;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect BikeLetRoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BikeLetRoleDataOnDemand: @Component;
    
    private Random BikeLetRoleDataOnDemand.rnd = new SecureRandom();
    
    private List<BikeLetRole> BikeLetRoleDataOnDemand.data;
    
    @Autowired
    private RolePermissionDataOnDemand BikeLetRoleDataOnDemand.rolePermissionDataOnDemand;
    
    @Autowired
    private UserRoleDataOnDemand BikeLetRoleDataOnDemand.userRoleDataOnDemand;
    
    public BikeLetRole BikeLetRoleDataOnDemand.getNewTransientBikeLetRole(int index) {
        BikeLetRole obj = new BikeLetRole();
        setRoleId(obj, index);
        setRoleName(obj, index);
        setRolePermissions(obj, index);
        setUsers(obj, index);
        return obj;
    }
    
    public void BikeLetRoleDataOnDemand.setRoleId(BikeLetRole obj, int index) {
        Integer roleId = new Integer(index);
        obj.setRoleId(roleId);
    }
    
    public void BikeLetRoleDataOnDemand.setRoleName(BikeLetRole obj, int index) {
        String roleName = "roleName_" + index;
        obj.setRoleName(roleName);
    }
    
    public void BikeLetRoleDataOnDemand.setRolePermissions(BikeLetRole obj, int index) {
        RolePermission rolePermissions = rolePermissionDataOnDemand.getRandomRolePermission();
        obj.setRolePermissions(rolePermissions);
    }
    
    public void BikeLetRoleDataOnDemand.setUsers(BikeLetRole obj, int index) {
        UserRole users = userRoleDataOnDemand.getRandomUserRole();
        obj.setUsers(users);
    }
    
    public BikeLetRole BikeLetRoleDataOnDemand.getSpecificBikeLetRole(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        BikeLetRole obj = data.get(index);
        java.lang.Long id = obj.getId();
        return BikeLetRole.findBikeLetRole(id);
    }
    
    public BikeLetRole BikeLetRoleDataOnDemand.getRandomBikeLetRole() {
        init();
        BikeLetRole obj = data.get(rnd.nextInt(data.size()));
        java.lang.Long id = obj.getId();
        return BikeLetRole.findBikeLetRole(id);
    }
    
    public boolean BikeLetRoleDataOnDemand.modifyBikeLetRole(BikeLetRole obj) {
        return false;
    }
    
    public void BikeLetRoleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = BikeLetRole.findBikeLetRoleEntries(from, to);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'BikeLetRole' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.sjsu.bikelet.domain.BikeLetRole>();
        for (int i = 0; i < 10; i++) {
            BikeLetRole obj = getNewTransientBikeLetRole(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
