// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.BillTransactionDataOnDemand;
import com.sjsu.bikelet.domain.BillTransactionIntegrationTest;
import com.sjsu.bikelet.service.BillTransactionService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BillTransactionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BillTransactionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BillTransactionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BillTransactionIntegrationTest: @Transactional;
    
    @Autowired
    private BillTransactionDataOnDemand BillTransactionIntegrationTest.dod;
    
    @Autowired
    BillTransactionService BillTransactionIntegrationTest.billTransactionService;
    
    @Test
    public void BillTransactionIntegrationTest.testCountAllBillTransactions() {
        Assert.assertNotNull("Data on demand for 'BillTransaction' failed to initialize correctly", dod.getRandomBillTransaction());
        long count = billTransactionService.countAllBillTransactions();
        Assert.assertTrue("Counter for 'BillTransaction' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BillTransactionIntegrationTest.testFindBillTransaction() {
        BillTransaction obj = dod.getRandomBillTransaction();
        Assert.assertNotNull("Data on demand for 'BillTransaction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BillTransaction' failed to provide an identifier", id);
        obj = billTransactionService.findBillTransaction(id);
        Assert.assertNotNull("Find method for 'BillTransaction' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BillTransaction' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BillTransactionIntegrationTest.testFindAllBillTransactions() {
        Assert.assertNotNull("Data on demand for 'BillTransaction' failed to initialize correctly", dod.getRandomBillTransaction());
        long count = billTransactionService.countAllBillTransactions();
        Assert.assertTrue("Too expensive to perform a find all test for 'BillTransaction', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BillTransaction> result = billTransactionService.findAllBillTransactions();
        Assert.assertNotNull("Find all method for 'BillTransaction' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BillTransaction' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BillTransactionIntegrationTest.testFindBillTransactionEntries() {
        Assert.assertNotNull("Data on demand for 'BillTransaction' failed to initialize correctly", dod.getRandomBillTransaction());
        long count = billTransactionService.countAllBillTransactions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BillTransaction> result = billTransactionService.findBillTransactionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BillTransaction' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BillTransaction' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BillTransactionIntegrationTest.testFlush() {
        BillTransaction obj = dod.getRandomBillTransaction();
        Assert.assertNotNull("Data on demand for 'BillTransaction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BillTransaction' failed to provide an identifier", id);
        obj = billTransactionService.findBillTransaction(id);
        Assert.assertNotNull("Find method for 'BillTransaction' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBillTransaction(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'BillTransaction' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BillTransactionIntegrationTest.testUpdateBillTransactionUpdate() {
        BillTransaction obj = dod.getRandomBillTransaction();
        Assert.assertNotNull("Data on demand for 'BillTransaction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BillTransaction' failed to provide an identifier", id);
        obj = billTransactionService.findBillTransaction(id);
        boolean modified =  dod.modifyBillTransaction(obj);
        Integer currentVersion = obj.getVersion();
        BillTransaction merged = billTransactionService.updateBillTransaction(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BillTransaction' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BillTransactionIntegrationTest.testSaveBillTransaction() {
        Assert.assertNotNull("Data on demand for 'BillTransaction' failed to initialize correctly", dod.getRandomBillTransaction());
        BillTransaction obj = dod.getNewTransientBillTransaction(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BillTransaction' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BillTransaction' identifier to be null", obj.getId());
        billTransactionService.saveBillTransaction(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'BillTransaction' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BillTransactionIntegrationTest.testDeleteBillTransaction() {
        BillTransaction obj = dod.getRandomBillTransaction();
        Assert.assertNotNull("Data on demand for 'BillTransaction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BillTransaction' failed to provide an identifier", id);
        obj = billTransactionService.findBillTransaction(id);
        billTransactionService.deleteBillTransaction(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'BillTransaction' with identifier '" + id + "'", billTransactionService.findBillTransaction(id));
    }
    
}
