// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.LicensePolicyDataOnDemand;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LicensePolicyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LicensePolicyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LicensePolicyIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LicensePolicyIntegrationTest: @Transactional;
    
    @Autowired
    private LicensePolicyDataOnDemand LicensePolicyIntegrationTest.dod;
    
    @Test
    public void LicensePolicyIntegrationTest.testCountLicensePolicys() {
        Assert.assertNotNull("Data on demand for 'LicensePolicy' failed to initialize correctly", dod.getRandomLicensePolicy());
        long count = LicensePolicy.countLicensePolicys();
        Assert.assertTrue("Counter for 'LicensePolicy' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LicensePolicyIntegrationTest.testFindLicensePolicy() {
        LicensePolicy obj = dod.getRandomLicensePolicy();
        Assert.assertNotNull("Data on demand for 'LicensePolicy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LicensePolicy' failed to provide an identifier", id);
        obj = LicensePolicy.findLicensePolicy(id);
        Assert.assertNotNull("Find method for 'LicensePolicy' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'LicensePolicy' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LicensePolicyIntegrationTest.testFindAllLicensePolicys() {
        Assert.assertNotNull("Data on demand for 'LicensePolicy' failed to initialize correctly", dod.getRandomLicensePolicy());
        long count = LicensePolicy.countLicensePolicys();
        Assert.assertTrue("Too expensive to perform a find all test for 'LicensePolicy', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<LicensePolicy> result = LicensePolicy.findAllLicensePolicys();
        Assert.assertNotNull("Find all method for 'LicensePolicy' illegally returned null", result);
        Assert.assertTrue("Find all method for 'LicensePolicy' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LicensePolicyIntegrationTest.testFindLicensePolicyEntries() {
        Assert.assertNotNull("Data on demand for 'LicensePolicy' failed to initialize correctly", dod.getRandomLicensePolicy());
        long count = LicensePolicy.countLicensePolicys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<LicensePolicy> result = LicensePolicy.findLicensePolicyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'LicensePolicy' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'LicensePolicy' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LicensePolicyIntegrationTest.testFlush() {
        LicensePolicy obj = dod.getRandomLicensePolicy();
        Assert.assertNotNull("Data on demand for 'LicensePolicy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LicensePolicy' failed to provide an identifier", id);
        obj = LicensePolicy.findLicensePolicy(id);
        Assert.assertNotNull("Find method for 'LicensePolicy' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLicensePolicy(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'LicensePolicy' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LicensePolicyIntegrationTest.testMergeUpdate() {
        LicensePolicy obj = dod.getRandomLicensePolicy();
        Assert.assertNotNull("Data on demand for 'LicensePolicy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LicensePolicy' failed to provide an identifier", id);
        obj = LicensePolicy.findLicensePolicy(id);
        boolean modified =  dod.modifyLicensePolicy(obj);
        Integer currentVersion = obj.getVersion();
        LicensePolicy merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'LicensePolicy' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LicensePolicyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'LicensePolicy' failed to initialize correctly", dod.getRandomLicensePolicy());
        LicensePolicy obj = dod.getNewTransientLicensePolicy(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'LicensePolicy' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'LicensePolicy' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'LicensePolicy' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LicensePolicyIntegrationTest.testRemove() {
        LicensePolicy obj = dod.getRandomLicensePolicy();
        Assert.assertNotNull("Data on demand for 'LicensePolicy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LicensePolicy' failed to provide an identifier", id);
        obj = LicensePolicy.findLicensePolicy(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'LicensePolicy' with identifier '" + id + "'", LicensePolicy.findLicensePolicy(id));
    }
    
}
