// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.Organization;
import com.sjsu.bikelet.domain.OrganizationDataOnDemand;
import com.sjsu.bikelet.domain.TenantDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect OrganizationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OrganizationDataOnDemand: @Component;
    
    private Random OrganizationDataOnDemand.rnd = new SecureRandom();
    
    private List<Organization> OrganizationDataOnDemand.data;
    
    @Autowired
    TenantDataOnDemand OrganizationDataOnDemand.tenantDataOnDemand;
    
    public Organization OrganizationDataOnDemand.getNewTransientOrganization(int index) {
        Organization obj = new Organization();
        setContactId(obj, index);
        setOrgName(obj, index);
        return obj;
    }
    
    public void OrganizationDataOnDemand.setContactId(Organization obj, int index) {
        Integer contactId = new Integer(index);
        obj.setContactId(contactId);
    }
    
    public void OrganizationDataOnDemand.setOrgName(Organization obj, int index) {
        String orgName = "orgName_" + index;
        if (orgName.length() > 30) {
            orgName = orgName.substring(0, 30);
        }
        obj.setOrgName(orgName);
    }
    
    public Organization OrganizationDataOnDemand.getSpecificOrganization(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Organization obj = data.get(index);
        Long id = obj.getId();
        return Organization.findOrganization(id);
    }
    
    public Organization OrganizationDataOnDemand.getRandomOrganization() {
        init();
        Organization obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Organization.findOrganization(id);
    }
    
    public boolean OrganizationDataOnDemand.modifyOrganization(Organization obj) {
        return false;
    }
    
    public void OrganizationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Organization.findOrganizationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Organization' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Organization>();
        for (int i = 0; i < 10; i++) {
            Organization obj = getNewTransientOrganization(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
