// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.PaymentTransactionDataOnDemand;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PaymentTransactionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PaymentTransactionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PaymentTransactionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PaymentTransactionIntegrationTest: @Transactional;
    
    @Autowired
    private PaymentTransactionDataOnDemand PaymentTransactionIntegrationTest.dod;
    
    @Test
    public void PaymentTransactionIntegrationTest.testCountPaymentTransactions() {
        Assert.assertNotNull("Data on demand for 'PaymentTransaction' failed to initialize correctly", dod.getRandomPaymentTransaction());
        long count = PaymentTransaction.countPaymentTransactions();
        Assert.assertTrue("Counter for 'PaymentTransaction' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PaymentTransactionIntegrationTest.testFindPaymentTransaction() {
        PaymentTransaction obj = dod.getRandomPaymentTransaction();
        Assert.assertNotNull("Data on demand for 'PaymentTransaction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PaymentTransaction' failed to provide an identifier", id);
        obj = PaymentTransaction.findPaymentTransaction(id);
        Assert.assertNotNull("Find method for 'PaymentTransaction' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PaymentTransaction' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PaymentTransactionIntegrationTest.testFindAllPaymentTransactions() {
        Assert.assertNotNull("Data on demand for 'PaymentTransaction' failed to initialize correctly", dod.getRandomPaymentTransaction());
        long count = PaymentTransaction.countPaymentTransactions();
        Assert.assertTrue("Too expensive to perform a find all test for 'PaymentTransaction', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PaymentTransaction> result = PaymentTransaction.findAllPaymentTransactions();
        Assert.assertNotNull("Find all method for 'PaymentTransaction' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PaymentTransaction' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PaymentTransactionIntegrationTest.testFindPaymentTransactionEntries() {
        Assert.assertNotNull("Data on demand for 'PaymentTransaction' failed to initialize correctly", dod.getRandomPaymentTransaction());
        long count = PaymentTransaction.countPaymentTransactions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PaymentTransaction> result = PaymentTransaction.findPaymentTransactionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PaymentTransaction' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PaymentTransaction' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PaymentTransactionIntegrationTest.testFlush() {
        PaymentTransaction obj = dod.getRandomPaymentTransaction();
        Assert.assertNotNull("Data on demand for 'PaymentTransaction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PaymentTransaction' failed to provide an identifier", id);
        obj = PaymentTransaction.findPaymentTransaction(id);
        Assert.assertNotNull("Find method for 'PaymentTransaction' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPaymentTransaction(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PaymentTransaction' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PaymentTransactionIntegrationTest.testMergeUpdate() {
        PaymentTransaction obj = dod.getRandomPaymentTransaction();
        Assert.assertNotNull("Data on demand for 'PaymentTransaction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PaymentTransaction' failed to provide an identifier", id);
        obj = PaymentTransaction.findPaymentTransaction(id);
        boolean modified =  dod.modifyPaymentTransaction(obj);
        Integer currentVersion = obj.getVersion();
        PaymentTransaction merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PaymentTransaction' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PaymentTransactionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PaymentTransaction' failed to initialize correctly", dod.getRandomPaymentTransaction());
        PaymentTransaction obj = dod.getNewTransientPaymentTransaction(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PaymentTransaction' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PaymentTransaction' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'PaymentTransaction' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PaymentTransactionIntegrationTest.testRemove() {
        PaymentTransaction obj = dod.getRandomPaymentTransaction();
        Assert.assertNotNull("Data on demand for 'PaymentTransaction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PaymentTransaction' failed to provide an identifier", id);
        obj = PaymentTransaction.findPaymentTransaction(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PaymentTransaction' with identifier '" + id + "'", PaymentTransaction.findPaymentTransaction(id));
    }
    
}
