// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.Permission;
import com.sjsu.bikelet.domain.PermissionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PermissionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PermissionDataOnDemand: @Component;
    
    private Random PermissionDataOnDemand.rnd = new SecureRandom();
    
    private List<Permission> PermissionDataOnDemand.data;
    
    public Permission PermissionDataOnDemand.getNewTransientPermission(int index) {
        Permission obj = new Permission();
        setDescription(obj, index);
        setPermissionName(obj, index);
        return obj;
    }
    
    public void PermissionDataOnDemand.setDescription(Permission obj, int index) {
        String description = "description_" + index;
        if (description.length() > 100) {
            description = description.substring(0, 100);
        }
        obj.setDescription(description);
    }
    
    public void PermissionDataOnDemand.setPermissionName(Permission obj, int index) {
        String permissionName = "permissionName_" + index;
        if (permissionName.length() > 30) {
            permissionName = permissionName.substring(0, 30);
        }
        obj.setPermissionName(permissionName);
    }
    
    public Permission PermissionDataOnDemand.getSpecificPermission(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Permission obj = data.get(index);
        Long id = obj.getId();
        return Permission.findPermission(id);
    }
    
    public Permission PermissionDataOnDemand.getRandomPermission() {
        init();
        Permission obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Permission.findPermission(id);
    }
    
    public boolean PermissionDataOnDemand.modifyPermission(Permission obj) {
        return false;
    }
    
    public void PermissionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Permission.findPermissionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Permission' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Permission>();
        for (int i = 0; i < 10; i++) {
            Permission obj = getNewTransientPermission(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
