// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.RentTransaction;
import com.sjsu.bikelet.domain.RentTransactionDataOnDemand;
import com.sjsu.bikelet.domain.RentTransactionIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RentTransactionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RentTransactionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RentTransactionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RentTransactionIntegrationTest: @Transactional;
    
    @Autowired
    RentTransactionDataOnDemand RentTransactionIntegrationTest.dod;
    
    @Test
    public void RentTransactionIntegrationTest.testCountRentTransactions() {
        Assert.assertNotNull("Data on demand for 'RentTransaction' failed to initialize correctly", dod.getRandomRentTransaction());
        long count = RentTransaction.countRentTransactions();
        Assert.assertTrue("Counter for 'RentTransaction' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RentTransactionIntegrationTest.testFindRentTransaction() {
        RentTransaction obj = dod.getRandomRentTransaction();
        Assert.assertNotNull("Data on demand for 'RentTransaction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RentTransaction' failed to provide an identifier", id);
        obj = RentTransaction.findRentTransaction(id);
        Assert.assertNotNull("Find method for 'RentTransaction' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RentTransaction' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RentTransactionIntegrationTest.testFindAllRentTransactions() {
        Assert.assertNotNull("Data on demand for 'RentTransaction' failed to initialize correctly", dod.getRandomRentTransaction());
        long count = RentTransaction.countRentTransactions();
        Assert.assertTrue("Too expensive to perform a find all test for 'RentTransaction', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RentTransaction> result = RentTransaction.findAllRentTransactions();
        Assert.assertNotNull("Find all method for 'RentTransaction' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RentTransaction' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RentTransactionIntegrationTest.testFindRentTransactionEntries() {
        Assert.assertNotNull("Data on demand for 'RentTransaction' failed to initialize correctly", dod.getRandomRentTransaction());
        long count = RentTransaction.countRentTransactions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RentTransaction> result = RentTransaction.findRentTransactionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RentTransaction' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RentTransaction' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RentTransactionIntegrationTest.testFlush() {
        RentTransaction obj = dod.getRandomRentTransaction();
        Assert.assertNotNull("Data on demand for 'RentTransaction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RentTransaction' failed to provide an identifier", id);
        obj = RentTransaction.findRentTransaction(id);
        Assert.assertNotNull("Find method for 'RentTransaction' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRentTransaction(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'RentTransaction' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RentTransactionIntegrationTest.testMergeUpdate() {
        RentTransaction obj = dod.getRandomRentTransaction();
        Assert.assertNotNull("Data on demand for 'RentTransaction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RentTransaction' failed to provide an identifier", id);
        obj = RentTransaction.findRentTransaction(id);
        boolean modified =  dod.modifyRentTransaction(obj);
        Integer currentVersion = obj.getVersion();
        RentTransaction merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'RentTransaction' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RentTransactionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'RentTransaction' failed to initialize correctly", dod.getRandomRentTransaction());
        RentTransaction obj = dod.getNewTransientRentTransaction(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RentTransaction' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RentTransaction' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'RentTransaction' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RentTransactionIntegrationTest.testRemove() {
        RentTransaction obj = dod.getRandomRentTransaction();
        Assert.assertNotNull("Data on demand for 'RentTransaction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RentTransaction' failed to provide an identifier", id);
        obj = RentTransaction.findRentTransaction(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'RentTransaction' with identifier '" + id + "'", RentTransaction.findRentTransaction(id));
    }
    
}
