// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.RolePermissionDataOnDemand;
import com.sjsu.bikelet.domain.RolePermissionIntegrationTest;
import com.sjsu.bikelet.service.RolePermissionService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RolePermissionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RolePermissionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RolePermissionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RolePermissionIntegrationTest: @Transactional;
    
    @Autowired
    RolePermissionDataOnDemand RolePermissionIntegrationTest.dod;
    
    @Autowired
    RolePermissionService RolePermissionIntegrationTest.rolePermissionService;
    
    @Test
    public void RolePermissionIntegrationTest.testCountAllRolePermissions() {
        Assert.assertNotNull("Data on demand for 'RolePermission' failed to initialize correctly", dod.getRandomRolePermission());
        long count = rolePermissionService.countAllRolePermissions();
        Assert.assertTrue("Counter for 'RolePermission' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RolePermissionIntegrationTest.testFindRolePermission() {
        RolePermission obj = dod.getRandomRolePermission();
        Assert.assertNotNull("Data on demand for 'RolePermission' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RolePermission' failed to provide an identifier", id);
        obj = rolePermissionService.findRolePermission(id);
        Assert.assertNotNull("Find method for 'RolePermission' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RolePermission' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RolePermissionIntegrationTest.testFindAllRolePermissions() {
        Assert.assertNotNull("Data on demand for 'RolePermission' failed to initialize correctly", dod.getRandomRolePermission());
        long count = rolePermissionService.countAllRolePermissions();
        Assert.assertTrue("Too expensive to perform a find all test for 'RolePermission', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RolePermission> result = rolePermissionService.findAllRolePermissions();
        Assert.assertNotNull("Find all method for 'RolePermission' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RolePermission' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RolePermissionIntegrationTest.testFindRolePermissionEntries() {
        Assert.assertNotNull("Data on demand for 'RolePermission' failed to initialize correctly", dod.getRandomRolePermission());
        long count = rolePermissionService.countAllRolePermissions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RolePermission> result = rolePermissionService.findRolePermissionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RolePermission' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RolePermission' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RolePermissionIntegrationTest.testFlush() {
        RolePermission obj = dod.getRandomRolePermission();
        Assert.assertNotNull("Data on demand for 'RolePermission' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RolePermission' failed to provide an identifier", id);
        obj = rolePermissionService.findRolePermission(id);
        Assert.assertNotNull("Find method for 'RolePermission' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRolePermission(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'RolePermission' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RolePermissionIntegrationTest.testUpdateRolePermissionUpdate() {
        RolePermission obj = dod.getRandomRolePermission();
        Assert.assertNotNull("Data on demand for 'RolePermission' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RolePermission' failed to provide an identifier", id);
        obj = rolePermissionService.findRolePermission(id);
        boolean modified =  dod.modifyRolePermission(obj);
        Integer currentVersion = obj.getVersion();
        RolePermission merged = rolePermissionService.updateRolePermission(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'RolePermission' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RolePermissionIntegrationTest.testSaveRolePermission() {
        Assert.assertNotNull("Data on demand for 'RolePermission' failed to initialize correctly", dod.getRandomRolePermission());
        RolePermission obj = dod.getNewTransientRolePermission(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RolePermission' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RolePermission' identifier to be null", obj.getId());
        rolePermissionService.saveRolePermission(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'RolePermission' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RolePermissionIntegrationTest.testDeleteRolePermission() {
        RolePermission obj = dod.getRandomRolePermission();
        Assert.assertNotNull("Data on demand for 'RolePermission' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RolePermission' failed to provide an identifier", id);
        obj = rolePermissionService.findRolePermission(id);
        rolePermissionService.deleteRolePermission(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'RolePermission' with identifier '" + id + "'", rolePermissionService.findRolePermission(id));
    }
    
}
