// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.BikeLetRoleDataOnDemand;
import com.sjsu.bikelet.domain.PermissionDataOnDemand;
import com.sjsu.bikelet.domain.RolePermission;
import com.sjsu.bikelet.domain.RolePermissionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect RolePermissionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RolePermissionDataOnDemand: @Component;
    
    private Random RolePermissionDataOnDemand.rnd = new SecureRandom();
    
    private List<RolePermission> RolePermissionDataOnDemand.data;
    
    @Autowired
    PermissionDataOnDemand RolePermissionDataOnDemand.permissionDataOnDemand;
    
    @Autowired
    BikeLetRoleDataOnDemand RolePermissionDataOnDemand.bikeLetRoleDataOnDemand;
    
    public RolePermission RolePermissionDataOnDemand.getNewTransientRolePermission(int index) {
        RolePermission obj = new RolePermission();
        return obj;
    }
    
    public RolePermission RolePermissionDataOnDemand.getSpecificRolePermission(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        RolePermission obj = data.get(index);
        Long id = obj.getId();
        return RolePermission.findRolePermission(id);
    }
    
    public RolePermission RolePermissionDataOnDemand.getRandomRolePermission() {
        init();
        RolePermission obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return RolePermission.findRolePermission(id);
    }
    
    public boolean RolePermissionDataOnDemand.modifyRolePermission(RolePermission obj) {
        return false;
    }
    
    public void RolePermissionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = RolePermission.findRolePermissionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'RolePermission' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<RolePermission>();
        for (int i = 0; i < 10; i++) {
            RolePermission obj = getNewTransientRolePermission(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
