// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.Tenant;
import com.sjsu.bikelet.domain.TenantDataOnDemand;
import com.sjsu.bikelet.domain.TenantIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TenantIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TenantIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TenantIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TenantIntegrationTest: @Transactional;
    
    @Autowired
    private TenantDataOnDemand TenantIntegrationTest.dod;
    
    @Test
    public void TenantIntegrationTest.testCountTenants() {
        Assert.assertNotNull("Data on demand for 'Tenant' failed to initialize correctly", dod.getRandomTenant());
        long count = Tenant.countTenants();
        Assert.assertTrue("Counter for 'Tenant' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TenantIntegrationTest.testFindTenant() {
        Tenant obj = dod.getRandomTenant();
        Assert.assertNotNull("Data on demand for 'Tenant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tenant' failed to provide an identifier", id);
        obj = Tenant.findTenant(id);
        Assert.assertNotNull("Find method for 'Tenant' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Tenant' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TenantIntegrationTest.testFindAllTenants() {
        Assert.assertNotNull("Data on demand for 'Tenant' failed to initialize correctly", dod.getRandomTenant());
        long count = Tenant.countTenants();
        Assert.assertTrue("Too expensive to perform a find all test for 'Tenant', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Tenant> result = Tenant.findAllTenants();
        Assert.assertNotNull("Find all method for 'Tenant' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Tenant' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TenantIntegrationTest.testFindTenantEntries() {
        Assert.assertNotNull("Data on demand for 'Tenant' failed to initialize correctly", dod.getRandomTenant());
        long count = Tenant.countTenants();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Tenant> result = Tenant.findTenantEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Tenant' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Tenant' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TenantIntegrationTest.testFlush() {
        Tenant obj = dod.getRandomTenant();
        Assert.assertNotNull("Data on demand for 'Tenant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tenant' failed to provide an identifier", id);
        obj = Tenant.findTenant(id);
        Assert.assertNotNull("Find method for 'Tenant' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTenant(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Tenant' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TenantIntegrationTest.testMergeUpdate() {
        Tenant obj = dod.getRandomTenant();
        Assert.assertNotNull("Data on demand for 'Tenant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tenant' failed to provide an identifier", id);
        obj = Tenant.findTenant(id);
        boolean modified =  dod.modifyTenant(obj);
        Integer currentVersion = obj.getVersion();
        Tenant merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Tenant' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TenantIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Tenant' failed to initialize correctly", dod.getRandomTenant());
        Tenant obj = dod.getNewTransientTenant(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Tenant' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Tenant' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Tenant' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TenantIntegrationTest.testRemove() {
        Tenant obj = dod.getRandomTenant();
        Assert.assertNotNull("Data on demand for 'Tenant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tenant' failed to provide an identifier", id);
        obj = Tenant.findTenant(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Tenant' with identifier '" + id + "'", Tenant.findTenant(id));
    }
    
}
