// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.UserSubscriptionPolicy;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UserSubscriptionPolicyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserSubscriptionPolicyDataOnDemand: @Component;
    
    private Random UserSubscriptionPolicyDataOnDemand.rnd = new SecureRandom();
    
    private List<UserSubscriptionPolicy> UserSubscriptionPolicyDataOnDemand.data;
    
    public UserSubscriptionPolicy UserSubscriptionPolicyDataOnDemand.getNewTransientUserSubscriptionPolicy(int index) {
        UserSubscriptionPolicy obj = new UserSubscriptionPolicy();
        return obj;
    }
    
    public UserSubscriptionPolicy UserSubscriptionPolicyDataOnDemand.getSpecificUserSubscriptionPolicy(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        UserSubscriptionPolicy obj = data.get(index);
        java.lang.Long id = obj.getId();
        return UserSubscriptionPolicy.findUserSubscriptionPolicy(id);
    }
    
    public UserSubscriptionPolicy UserSubscriptionPolicyDataOnDemand.getRandomUserSubscriptionPolicy() {
        init();
        UserSubscriptionPolicy obj = data.get(rnd.nextInt(data.size()));
        java.lang.Long id = obj.getId();
        return UserSubscriptionPolicy.findUserSubscriptionPolicy(id);
    }
    
    public boolean UserSubscriptionPolicyDataOnDemand.modifyUserSubscriptionPolicy(UserSubscriptionPolicy obj) {
        return false;
    }
    
    public void UserSubscriptionPolicyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UserSubscriptionPolicy.findUserSubscriptionPolicyEntries(from, to);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'UserSubscriptionPolicy' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.sjsu.bikelet.domain.UserSubscriptionPolicy>();
        for (int i = 0; i < 10; i++) {
            UserSubscriptionPolicy obj = getNewTransientUserSubscriptionPolicy(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
