// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import com.sjsu.bikelet.domain.BikeLetRole;

privileged aspect BikeLetRole_Roo_JavaBean {
    
    public String BikeLetRole.getRoleName() {
        return this.roleName;
    }
    
    public void BikeLetRole.setRoleName(String roleName) {
        this.roleName = roleName;
    }
    
}
