// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.bikelet.domain;

import java.lang.String;

privileged aspect BikeLocation_Roo_JavaBean {
    
    public String BikeLocation.getBikeStatus() {
        return this.bikeStatus;
    }
    
    public void BikeLocation.setBikeStatus(String bikeStatus) {
        this.bikeStatus = bikeStatus;
    }
    
}
